// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Mock_Project.Models;

public partial class db_xemphimContext : DbContext
{
    public db_xemphimContext()
    {
    }

    public db_xemphimContext(DbContextOptions<db_xemphimContext> options)
        : base(options)
    {
    }

    public virtual DbSet<PHIM> PHIM { get; set; }

    public virtual DbSet<PHONG> PHONG { get; set; }

    public virtual DbSet<RAP> RAP { get; set; }

    public virtual DbSet<SUATCHIEU> SUATCHIEU { get; set; }

    public virtual DbSet<TAIKHOAN> TAIKHOAN { get; set; }

    public virtual DbSet<VEPHIM> VEPHIM { get; set; }


    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<PHIM>(entity =>
        {

            entity.HasKey(e => e.MaPhim).HasName("PK__PHIM__4AC03DE3C61F2191");

            entity.HasKey(e => e.MaPhim).HasName("PK__PHIM__4AC03DE3A6E2E1A5");


            entity.Property(e => e.Anh)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.MoTa).HasColumnType("text");
            entity.Property(e => e.TenPhim)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.TheLoai)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.ThoiLuong)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PHONG>(entity =>
        {

            entity.HasKey(e => e.MaPhong).HasName("PK__PHONG__20BD5E5BB55A4C63");

            entity.HasKey(e => e.MaPhong).HasName("PK__PHONG__20BD5E5B9CF3BB84");


            entity.Property(e => e.TenPhong)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.MaRapNavigation).WithMany(p => p.PHONG)
                .HasForeignKey(d => d.MaRap)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__PHONG__MaRap__4D94879B");
        });

        modelBuilder.Entity<RAP>(entity =>
        {

            entity.HasKey(e => e.MaRap).HasName("PK__RAP__3961207FD7B9B51A");

            entity.HasKey(e => e.MaRap).HasName("PK__RAP__3961207FC3A9C024");


            entity.Property(e => e.Anh)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.DiaChi)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.SDT)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.TenRap)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<SUATCHIEU>(entity =>
        {

            entity.HasKey(e => e.MaSuatChieu).HasName("PK__SUATCHIE__CF5984D297A065BC");

            entity.HasKey(e => e.MaSuatChieu).HasName("PK__SUATCHIE__CF5984D268EF1453");


            entity.Property(e => e.NgayChieu).HasColumnType("datetime");

            entity.HasOne(d => d.MaPhimNavigation).WithMany(p => p.SUATCHIEU)
                .HasForeignKey(d => d.MaPhim)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SUATCHIEU__MaPhi__5070F446");

            entity.HasOne(d => d.MaPhongNavigation).WithMany(p => p.SUATCHIEU)
                .HasForeignKey(d => d.MaPhong)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__SUATCHIEU__MaPho__5165187F");
        });

        modelBuilder.Entity<TAIKHOAN>(entity =>
        {

            entity.HasKey(e => e.MaTK).HasName("PK__TAIKHOAN__272500705F801E14");

            entity.Property(e => e.DiaChi)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.MatKhau)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SDT)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TenNguoiDung)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.TenTK)
                .IsRequired()
                .HasMaxLength(100)

            entity.HasKey(e => e.MaTK).HasName("PK__TAIKHOAN__27250070872CB56E");

            entity.Property(e => e.DiaChi)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.Email)
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.MatKhau)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.SDT)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.TenNguoiDung)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
            entity.Property(e => e.TenTK)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false);
        });

        modelBuilder.Entity<VEPHIM>(entity =>
        {

            entity.HasKey(e => e.MaVe).HasName("PK__VEPHIM__2725100F94EB4B4B");

            entity.HasKey(e => e.MaVe).HasName("PK__VEPHIM__2725100FD97866ED");


            entity.Property(e => e.PTTT)
                .HasMaxLength(255)
                .IsUnicode(false);

            entity.HasOne(d => d.MaSuatChieuNavigation).WithMany(p => p.VEPHIM)
                .HasForeignKey(d => d.MaSuatChieu)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VEPHIM__MaSuatCh__571DF1D5");

            entity.HasOne(d => d.MaTKNavigation).WithMany(p => p.VEPHIM)
                .HasForeignKey(d => d.MaTK)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VEPHIM__MaTK__5629CD9C");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}