// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class PHIM
{
    public int MaPhim { get; set; }

    public string TenPhim { get; set; }

    public string TheLoai { get; set; }

    public string ThoiLuong { get; set; }

    public TimeOnly? KhoiChieu { get; set; }

    public string Anh { get; set; }

    public string MoTa { get; set; }

    public virtual ICollection<SUATCHIEU> SUATCHIEU { get; set; } = new List<SUATCHIEU>();
}