// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class PHONG
{
    public int MaPhong { get; set; }

    public int MaRap { get; set; }

    public string TenPhong { get; set; }

    public int SoLuongGhe { get; set; }

    public virtual RAP MaRapNavigation { get; set; }

    public virtual ICollection<SUATCHIEU> SUATCHIEU { get; set; } = new List<SUATCHIEU>();
}