// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class RAP_IMAGE
{
    public int MaRap { get; set; }

    public string TenRap { get; set; }

    public string DiaChi { get; set; }

    //public string Anh { get; set; }

    public string SDT { get; set; }

    public IFormFile Anh { get; set; }
}