// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class ROLE
{
    public int MaRole { get; set; }

    public string TenRole { get; set; }

    public virtual ICollection<TAIKHOAN> TAIKHOAN { get; set; } = new List<TAIKHOAN>();
}