// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class SUATCHIEU
{
    public int MaSuatChieu { get; set; }

    public int MaPhim { get; set; }

    public int MaPhong { get; set; }

    public DateTime? NgayChieu { get; set; }

    public TimeOnly? ThoiGianBatDau { get; set; }

    public virtual PHIM MaPhimNavigation { get; set; }

    public virtual PHONG MaPhongNavigation { get; set; }

    public virtual ICollection<VEPHIM> VEPHIM { get; set; } = new List<VEPHIM>();
}