// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class TAIKHOAN
{
    public int MaTK { get; set; }

    public string TenTK { get; set; }

    public string MatKhau { get; set; }

    public string DiaChi { get; set; }

    public DateOnly? NgaySinh { get; set; }

    public string Email { get; set; }

    public string SDT { get; set; }

    public string TenNguoiDung { get; set; }

    public virtual ICollection<VEPHIM> VEPHIM { get; set; } = new List<VEPHIM>();
}