// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Mock_Project.Models;

public partial class VEPHIM
{
    public int MaVe { get; set; }

    public int MaSuatChieu { get; set; }

    public int MaTK { get; set; }

    public int? GiaVe { get; set; }

    public string PTTT { get; set; }

    public int? ViTri { get; set; }

    public virtual SUATCHIEU MaSuatChieuNavigation { get; set; }

    public virtual TAIKHOAN MaTKNavigation { get; set; }
}